model:
  decoderconfig:
    double_z: False
    z_channels: 32 # origin 256
    resolution: 256
    in_channels: 3
    out_ch: 3
    ch: 128
    ch_mult: [1,2,4] # origin (1,1,2,2,4)
    num_res_blocks: 2
    attn_resolutions: []
    dropout: 0.0
  gpsconfig:
    rois: 8
    gpsenc_n: 30
    gpsenc_c: 512
    gps_c: 32
    gps_num: 256
    gps_dmax: 3
    gps_adaptive_w: 2.5
    gps_rs: [64, 64]

train:
  lr: 5.0e-5
  batch_size: 16
  grad_accumulation: 1
  iterations: 1000000
  log_interval: 100
  save_interval: 50000
  eval_interval: 5000

loss:
  perceptual:
    target: fid
    weight: 1.0
  discriminator:
    disc_conditional: False
    disc_in_channels: 3
    disc_start: 600000
    disc_weight: 0.30
    codebook_weight: 1.0
    perceptual_weight: 1.0

data:
  target: AdaptiveGPSDataset
  num_workers: 16
  params:
      paths_or_file: datasets/data/imagenet_train.txt
      size: 256
